name: Run Migrations and Update Challenges

on:
  push:
    branches:
      - main

jobs:
  run_migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PNPM_HOME: /pnpm
      PATH: $/pnpm:${{ env.PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: corepack enable pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Migrations
        run: |
          cd packages/db \
          npx prisma migrate dev
      - name: Update Challenges
        run: |
          cd packages/db \
          npx tsc && node dist/scripts/index.js


